{
    'name': 'Salon Management',
    'version': '11.0.0.1',
    'summary': 'Salon Management',
    'category': 'Salon',
    'author': 'Jakc Labs',
    'company': 'Jakc Labs',
    'maintainer': 'Jakc Labs',
    'depends': ['sale','account', 'purchase', 'stock', 'hr',],
    'website': 'https://www.jakc-labs.com',
    'data': [
        'security/ir.model.access.csv',
        'wizard/wizard_add_workorder_employee_view.xml',
        'views/jakc_salon_menu.xml',
        'views/booking_view.xml',
        'views/sale_view.xml',
        'views/product_template_view.xml',
        'views/hr_view.xml',
        'report/report_employee_commission_templates.xml',
        'views/jakc_salon_mgmt_report.xml',

    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}